### ISSUE TITLE
Omit boxplot whiskers, as in coef=0 in geom_boxplot()?

### ISSUE THREAD

**Issue by jmwhyte** [cran/ggpubr#2]
Sometimes it's appropriate to not show the whiskers in a boxplot. How can we achieve this using ggboxplot?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by jmwhyte** [comment]
Hello,
thanks for advising me of this error.
Best regards,
Jason

Jason Whyte, PhD
website: https://jmwhyte.github.io/
Research Associate CEER (School of BioSciences), and
visiting researcher School of Mathematics and Statistics,
The University of Melbourne 3010, Victoria AUSTRALIA
________________________________
From: Gábor Csárdi ***@***.***>
Sent: Wednesday, November 23, 2022 7:13 PM
To: cran/ggpubr ***@***.***>
Cc: Jason Whyte ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [cran/ggpubr] Omit boxplot whiskers, as in coef=0 in geom_boxplot()? (Issue #2)


External email: Please exercise caution

________________________________
Hi, this is a read only mirror of CRAN, please see the package authors in the DESCRIPTION file. Look for Maintainer, BugReports and URL. Thanks!
